repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: "trailing-whitespace"
        exclude: ^searxng/settings\.yml$
      - id: "check-case-conflict"
      - id: "check-merge-conflict"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
        exclude: ^searxng/settings\.yml$
      - id: "mixed-line-ending"
      - id: "detect-private-key"
      - id: "check-yaml"
      - id: "check-toml"
      - id: "check-json"
